[project]
name = "cronwatchbot"
version = "2.1"
description = "Manage urlwatch and crontab via Telegram"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-crontab>=3.3.0",
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.7",
    "pyyaml>=6.0.3",
    "urlwatch>=2.29",
]
